# frozen_string_literal: true

# ONLY USE beams that are extrusions of 44×69 — orientation free: one rectangular face must be
# 44 mm × 69 mm; the third dimension is only the extrusion length (any value).

# Extendable interlocking-slats bed: back (head) frame + front (foot) frame.
# SketchUp uses inches internally; dimensions below use .mm.
#
# Design is driven by actual section size and cut lengths — not nominal 800/2000/etc.
# TOP_OF_SLATS_Z is the world +Z of the upper face of the comb slats (not the plank ledges above them).
# Main inputs live in ExtendableBed after LAYER_NAME; SLAT_LENGTH = LENGTH_EXTENDED/2;
# BACK_SLAT_RUN_Y / FRONT_SLAT_RUN_Y = SLAT_LENGTH + BEAM_Y. PillowFactory uses PILLOW_THICKNESS on every pillow prism.
#
# Coordinates: +Y head → foot (extension). +Z up. Slats run parallel to Y.
# create places three side-by-side pairs along +X: extended, half-extended, retracted (pillow previews).

module Timmerman
  module ExtendableBed
    LAYER_NAME = 'EB_ExtendableBed'

    # Main inputs:
    BACK_SLAT_COUNT = 9 # Back comb tooth count must be odd — layout (outer sisters, ties, mid legs)
    TOP_OF_SLATS_Z = 300.mm # Upper face of comb slats (+Z).
    LENGTH_EXTENDED = 2000.mm # Extended bed length.

    unless BACK_SLAT_COUNT.is_a?(Integer) && BACK_SLAT_COUNT.positive? && BACK_SLAT_COUNT.odd?
      raise ArgumentError, "ExtendableBed: BACK_SLAT_COUNT must be a positive odd integer (got #{BACK_SLAT_COUNT.inspect})"
    end

    # Material dimensions (based on standard stock dimensions)
    BEAM_NARROW = 44.mm
    BEAM_WIDE = 69.mm
    PLANK_THICKNESS = 18.mm
    PILLOW_THICKNESS = 100.mm

    # Slat dimensions:
    SLAT_GAP = 3.mm

    # Dimensions related to variants:
    PAIR_GAP_X = 600.mm

    # Stock dimensions:
    BEAM_STOCK_BAR_LENGTH = 2100.mm


    # --- Derived from main inputs ---
    # Front slat count: one fewer than back (front sits in gaps of back).
    FRONT_SLAT_COUNT = BACK_SLAT_COUNT - 1
    # Slats: narrow edge along bed width (X), wide edge vertical (Z) — stiffer in bending
    SLAT_DX = BEAM_NARROW
    SLAT_DZ = BEAM_WIDE
    # End beams: narrow along run (Y), wide vertical (Z). Head/foot caps: same sawn face; full width X; depth Y = BEAM_Y.
    BEAM_Y = BEAM_NARROW
    BEAM_Z = BEAM_WIDE
    # Leg posts: wide along X (across comb), narrow along Y (parallel to slat run)
    LEG_X = BEAM_WIDE
    LEG_Y = BEAM_NARROW
    # Half the open span per slat run; end beams supply structural overlap along Y.
    SLAT_LENGTH = LENGTH_EXTENDED / 2
    BACK_SLAT_RUN_Y = SLAT_LENGTH + BEAM_Y
    FRONT_SLAT_RUN_Y = BACK_SLAT_RUN_Y
    LENGTH_RETRACTED = BACK_SLAT_RUN_Y + BEAM_Y
    EXTENDED_FRONT_FOOT_WORLD_Y = LENGTH_EXTENDED
    RETRACTED_FOOT_WORLD_Y = LENGTH_RETRACTED + BEAM_NARROW
    N_SLATS_X = BACK_SLAT_COUNT + FRONT_SLAT_COUNT
    GAPS_ALONG_X = N_SLATS_X - 1
    OUTER_WIDTH =
      (N_SLATS_X * SLAT_DX) +
      (GAPS_ALONG_X * SLAT_GAP)

    GROUP_EXT_BACK = 'EB_Ext_Back'
    GROUP_EXT_FRONT = 'EB_Ext_Front'
    GROUP_RET_BACK = 'EB_Ret_Back'
    GROUP_RET_FRONT = 'EB_Ret_Front'
    GROUP_HALF_BACK = 'EB_Half_Back'
    GROUP_HALF_FRONT = 'EB_Half_Front'

    EB_GROUP_NAME_RE = /\AEB_(Ext|Ret|Half)_(Back|Front)\z/
    # Single-pair bed roots (cleared together with EB_Ext_* / EB_Ret_* / EB_Half_*).
    EB_SINGLE_PAIR_ROOTS = %w[EB_Back EB_Front].freeze

    # Design-reference bed copies in the model (not regenerated by create). clear must not recurse into
    # these subtrees when purging legacy names, so nested parts keep exact outliner names.
    EB_REFERENCE_ROOT_NAME_RE = /\A(?:NEW|New)_EB_Ext_(Back|Front)\z/

    # Unqualified mid behind-leg outliner names (current geometry uses HEADWARD_BEHIND_LEG_MID_*).
    # Purged on clear (skipping EB_REFERENCE_ROOT_NAME_RE subtrees) so stray copies are removed.
    BEHIND_LEG_MID_UNQUALIFIED_NAMES = %w[
      EB | beam | behind leg | mid -X
      EB | beam | behind leg | mid +X
    ].freeze
    HEADWARD_BEHIND_LEG_MID_NEG_X = 'EB | beam | behind leg | mid -X | headward'
    HEADWARD_BEHIND_LEG_MID_POS_X = 'EB | beam | behind leg | mid +X | headward'
    # Vertical 69×44×lh_mid beside inner face of mid leg; top z = lh_mid under mid tie (same Y band as tie).
    MID_TIE_VERTICAL_FILLER_NEG_X = 'EB | beam | mid tie | vertical filler | -X'
    MID_TIE_VERTICAL_FILLER_POS_X = 'EB | beam | mid tie | vertical filler | +X'
    HEAD_TIE_BETWEEN_SISTERS = 'EB | beam | head tie | between sisters'
    FRONT_RIGIDITY_BEAM_BELOW_CAP = 'EB | beam | front | rigidity | below foot cap'

    # Footward (−Y) placement: beam spans up to y = −BEAM_Y (flush with foot-leg / cap plane) so validate has no false AABB hits.
    FRONT_RIGIDITY_BEAM_Y0 = (-2 * BEAM_Y)

    # Big: retracted span + BEAM_NARROW so it sits between head/foot planks; each small is half of the remainder so extended run still sums to LENGTH_EXTENDED:
    # PILLOW_BIG_LENGTH + 2×PILLOW_SMALL_LENGTH = LENGTH_EXTENDED.
    PILLOW_BIG_LENGTH = LENGTH_RETRACTED + BEAM_NARROW
    PILLOW_SMALL_LENGTH = (LENGTH_EXTENDED - LENGTH_RETRACTED - BEAM_NARROW) / 2

    # Half-extended pair: open span head→foot = PILLOW_BIG_LENGTH + PILLOW_SMALL_LENGTH (= LENGTH_EXTENDED − PILLOW_SMALL_LENGTH).
    HALFWAY_FRONT_FOOT_WORLD_Y = PILLOW_BIG_LENGTH + PILLOW_SMALL_LENGTH

    # Named planks (non-stock): Outliner prefix and known part names — use only via PlankFactory.
    EB_PLANK_NAME_RE = /\AEB \| plank \|/
    PLANK_FOOT_LEDGE = 'EB | plank | foot | ledge'
    PLANK_HEAD_LEDGE = 'EB | plank | head | ledge'

    # Named pillows — use only via PillowFactory (+PILLOW_THICKNESS).
    EB_PILLOW_NAME_RE = /\AEB \| pillow \|/
    PILLOW_BIG = 'EB | pillow | big'
    PILLOW_SMALL_1 = 'EB | pillow | small | 1'
    PILLOW_SMALL_2 = 'EB | pillow | small | 2'
    PILLOW_COUCH_HEAD = 'EB | pillow | couch | head'
    PILLOW_COUCH_RIGHT = 'EB | pillow | couch | right'

    # Beams + legs only (excludes slats); used for overlap checks between structural solids.
    EB_SOLID_NAME_RE = /\AEB \| (beam|leg) \|/

    module_function

    # Always use model root for EB geometry. +active_entities+ follows edit context; mixing it with
    # +clear+ left top-level beds in place while nesting new runs (duplicate roots, false overlaps).
    def placement_entities(model)
      model.entities
    end

    # SketchUp raises if you erase an entity on the active edit path; pop all nested edits first.
    def exit_edit_context!(model)
      while model.close_active
      end
    end

    # Erase nested groups by exact name (Groups only). With +skip_reference_subtrees+, does not recurse into
    # EB_REFERENCE_ROOT_NAME_RE roots (design copies in the model).
    def purge_named_groups_recursive(entities, names_to_erase, skip_reference_subtrees: false)
      entities.to_a.each do |e|
        next unless e.valid?
        next unless e.is_a?(Sketchup::Group)
        next if skip_reference_subtrees && EB_REFERENCE_ROOT_NAME_RE.match?(e.name)

        purge_named_groups_recursive(e.entities, names_to_erase, skip_reference_subtrees: skip_reference_subtrees)
        e.erase! if names_to_erase.include?(e.name)
      end
    end

    def z_slat_top
      TOP_OF_SLATS_Z
    end

    def z_slat_bottom
      z_slat_top - SLAT_DZ
    end

    # Same +Z as slat lower face: end beams and slats share z_low in build_back_geometry / build_front_geometry.
    def z_beam_bottom
      z_slat_bottom
    end

    def z_leg_top
      z_beam_bottom - BEAM_Z
    end

    def leg_height
      z_leg_top
    end

    # Head and foot frames: outer -X/+X corner legs run through the cap band so the shortened end cap bears on their inner ±X faces.
    # Inset corner legs stay at +leg_height+.
    def outer_corner_leg_height_through_cap
      z_beam_bottom
    end

    # Mid-run legs share X with outer comb columns; tops must stop at sister-beam bottom (no Z overlap).
    def mid_run_leg_height(z_slats)
      z_slats - BEAM_Z
    end

    def outer_width
      OUTER_WIDTH
    end

    def ensure_layer(model)
      layer = model.layers[LAYER_NAME]
      layer ||= model.layers.add(LAYER_NAME)
      layer
    end

    # Shaded-view preview: back (fixed) vs front (sliding) root groups. RGB 0–255; edit to taste.
    EB_PREVIEW_MAT_BACK = 'EB preview | back'.freeze
    EB_PREVIEW_MAT_FRONT = 'EB preview | front'.freeze
    EB_PREVIEW_RGB_BACK = [188, 152, 106].freeze
    # Same warm wood family as back; a step deeper so front vs back reads more clearly in shaded view.
    EB_PREVIEW_RGB_FRONT = [168, 130, 90].freeze

    def ensure_preview_material(model, name, rgb)
      m = model.materials[name] || model.materials.add(name)
      m.color = Sketchup::Color.new(rgb[0], rgb[1], rgb[2])
      m
    end

    # Paints every face under a root group (nested named part groups).
    def paint_entities_preview_color(entities, material)
      entities.each do |e|
        case e
        when Sketchup::Face
          e.material = material
          e.back_material = material
        when Sketchup::Group
          paint_entities_preview_color(e.entities, material)
        when Sketchup::ComponentInstance
          paint_entities_preview_color(e.definition.entities, material)
        end
      end
    end

    def paint_root_group_preview_color(group, model, rgb, material_name)
      paint_entities_preview_color(group.entities, ensure_preview_material(model, material_name, rgb))
    end

    ATTR_DICT = 'Timmerman::ExtendableBed'

    # Millimetres — all stock checks and usage tallies are metric (SU stores lengths internally as Length).
    BEAM_SECTION_TOL_MM = 0.01

    # `create` builds three side-by-side pairs (extended + retracted + half-extended previews). Stock metre count and cut plan
    # only include the first pair — one physical bed (GROUP_EXT_BACK + GROUP_EXT_FRONT).

    # Subtracted between consecutive cuts from the same bar (blade kerf). 0 if you nest cuts in planning only.
    BEAM_STOCK_KERF_MM = 0.0

    def reset_beam_stock_usage!
      @beam_stock_extrusion_m = 0.0
      @beam_stock_piece_count = 0
      @beam_stock_cuts = []
      @eb_stock_tally = true
    end

    # When false, `add_stock_beam` still creates geometry but does not update cut list / metre tally.
    def stock_tally?
      @eb_stock_tally != false
    end

    def beam_stock_extrusion_m
      @beam_stock_extrusion_m ||= 0.0
    end

    def beam_stock_piece_count
      @beam_stock_piece_count ||= 0
    end

    # Each physical prism tallied for stock: `{ name:, mm: }` (mm along extrusion).
    def beam_stock_cuts
      @beam_stock_cuts ||= []
    end

    # Sum of cut lengths + kerf between cuts on one bar (order-independent).
    def beam_bar_used_mm(parts, kerf_mm)
      return 0.0 if parts.nil? || parts.empty?

      k = kerf_mm.to_f
      parts.sum { |p| p[:mm].to_f } + (parts.size > 1 ? k * (parts.size - 1) : 0.0)
    end

    def beam_bins_deep_dup(bins)
      bins.map { |b| { parts: b[:parts].map { |p| { name: p[:name], mm: p[:mm].to_f } } } }
    end

    # Lexicographic: fewer bars first, then less total offcut (mm).
    def beam_packing_lex_score(bins, stock_mm, kerf_mm)
      kerf = kerf_mm.to_f
      waste = bins.sum { |b| stock_mm - beam_bar_used_mm(b[:parts], kerf) }
      [bins.size, waste]
    end

    # SketchUp Ruby may not define Array#< for lexicographic compare.
    def beam_packing_score_better?(candidate, than)
      return true if than.nil?

      c0, c1 = candidate[0], candidate[1]
      t0, t1 = than[0], than[1]
      c0 < t0 || (c0 == t0 && c1 < t1)
    end

    def beam_pack_ffd_decreasing(list, stock_mm, kerf_mm, tol)
      kerf = kerf_mm.to_f
      bins = []
      list.sort_by! { |c| [-c[:mm], c[:name].to_s] }
      list.each do |cut|
        c = { name: cut[:name], mm: cut[:mm].to_f }
        placed = bins.any? do |bar|
          trial = bar[:parts] + [c]
          next false if beam_bar_used_mm(trial, kerf) > stock_mm + tol

          bar[:parts] << c
          true
        end
        bins << { parts: [c] } unless placed
      end
      bins
    end

    # Tightest-fit bar first (smallest slack after placing the cut).
    def beam_pack_bfd_decreasing(list, stock_mm, kerf_mm, tol)
      kerf = kerf_mm.to_f
      bins = []
      list.sort_by! { |c| [-c[:mm], c[:name].to_s] }
      list.each do |cut|
        c = { name: cut[:name], mm: cut[:mm].to_f }
        best_bar = nil
        best_slack = nil
        bins.each do |bar|
          trial = bar[:parts] + [c]
          u = beam_bar_used_mm(trial, kerf)
          next if u > stock_mm + tol

          slack = stock_mm - u
          if best_slack.nil? || slack < best_slack
            best_slack = slack
            best_bar = bar
          end
        end
        if best_bar
          best_bar[:parts] << c
        else
          bins << { parts: [c] }
        end
      end
      bins
    end

    # Greedy: move one cut to another bar if it reduces (bar count, total waste).
    def beam_improve_bins_local!(bins, stock_mm, kerf_mm, tol)
      kerf = kerf_mm.to_f
      loop do
        baseline = beam_packing_lex_score(bins, stock_mm, kerf)
        best_candidate = nil
        best_score = baseline

        bins.size.times do |i|
          bins.size.times do |j|
            next if i == j

            donor = bins[i]
            donor[:parts].each_index do |pi|
              trial = beam_bins_deep_dup(bins)
              p = trial[i][:parts].delete_at(pi)
              next if p.nil?

              trial[j][:parts] << p
              trial.reject! { |b| b[:parts].empty? }
              next if trial.any? { |b| beam_bar_used_mm(b[:parts], kerf) > stock_mm + tol }

              sc = beam_packing_lex_score(trial, stock_mm, kerf)
              next unless beam_packing_score_better?(sc, best_score)

              best_score = sc
              best_candidate = trial
            end
          end
        end

        break if best_candidate.nil?

        bins.replace(best_candidate)
      end
      bins
    end

    def beam_finalize_bins(bins, stock_mm, kerf_mm)
      kerf = kerf_mm.to_f
      bins.map do |bar|
        u = beam_bar_used_mm(bar[:parts], kerf)
        { used_mm: u, waste_mm: stock_mm - u, parts: bar[:parts].map(&:dup) }
      end
    end

    # Packs cuts into stock bars: tries First Fit Decreasing, Best Fit Decreasing, each with optional
    # local improvement (single-cut relocations), and keeps the best (fewest bars, then least total offcut).
    # Returns `{ ok: true, bars: [ { used_mm:, waste_mm:, parts: [{name, mm}, ...] }, ... ] }` or
    # `{ ok: false, oversize: [{name, mm}, ...] }` if any cut exceeds +stock_mm+.
    def pack_beam_cuts_into_bars(cuts, stock_mm, kerf_mm: BEAM_STOCK_KERF_MM)
      tol = BEAM_SECTION_TOL_MM
      list = cuts.map { |c| { name: c[:name], mm: c[:mm].to_f } }
      oversize = list.select { |c| c[:mm] > stock_mm + tol }
      return { ok: false, oversize: oversize } unless oversize.empty?

      kerf = kerf_mm.to_f
      seeds = []
      seeds << beam_pack_ffd_decreasing(list.map(&:dup), stock_mm, kerf, tol)
      seeds << beam_pack_bfd_decreasing(list.map(&:dup), stock_mm, kerf, tol)

      best_bins = nil
      best_score = nil
      seeds.each do |raw|
        [false, true].each do |improve|
          b = beam_bins_deep_dup(raw)
          beam_improve_bins_local!(b, stock_mm, kerf, tol) if improve
          sc = beam_packing_lex_score(b, stock_mm, kerf)
          if best_score.nil? || beam_packing_score_better?(sc, best_score)
            best_score = sc
            best_bins = b
          end
        end
      end

      { ok: true, bars: beam_finalize_bins(best_bins, stock_mm, kerf) }
    end

    def puts_beam_stock_cut_plan(cuts = beam_stock_cuts, stock_length: BEAM_STOCK_BAR_LENGTH, kerf_mm: BEAM_STOCK_KERF_MM)
      stock_mm = stock_length.to_mm
      kerf = kerf_mm.to_f
      result = pack_beam_cuts_into_bars(cuts, stock_mm, kerf_mm: kerf)
      unless result[:ok]
        puts '[EB stock] Cut plan: some pieces are longer than one stock bar — increase BEAM_STOCK_BAR_LENGTH or shorten cuts:'
        result[:oversize].each { |c| puts format('  %s — %.1f mm (bar %.1f mm)', c[:name], c[:mm], stock_mm) }
        return result
      end

      bars = result[:bars]
      total_waste = bars.sum { |b| b[:waste_mm] }
      sum_cuts = cuts.sum { |c| c[:mm].to_f }
      puts format('[EB stock] Cut plan (same scope as metre/piece tally): %.1f mm bars, %d bar(s) for %d cut(s); total cut length %.1f mm; combined offcuts %.1f mm (%.3f m). (best of FFD/BFD + local moves)',
                  stock_mm, bars.size, cuts.size, sum_cuts, total_waste, total_waste / 1000.0)
      puts '  Kerf between cuts on the same bar is included (see BEAM_STOCK_KERF_MM).' if kerf > 0

      bars.each_with_index do |bar, i|
        puts format('  Bar %d: used %.1f mm, offcut %.1f mm', i + 1, bar[:used_mm], bar[:waste_mm])
        bar[:parts].each do |p|
          puts format('    — %.1f mm  %s', p[:mm], p[:name])
        end
      end
      result
    end

    def stock_section_match?(len)
      v = len.to_mm.abs
      n = BEAM_NARROW.to_mm
      w = BEAM_WIDE.to_mm
      (v - n).abs < BEAM_SECTION_TOL_MM || (v - w).abs < BEAM_SECTION_TOL_MM
    end

    # One prism dimension is extrusion length; the other two must be BEAM_NARROW × BEAM_WIDE (order free).
    def extrusion_length_mm(dx, dy, dz)
      dims = [dx, dy, dz]
      unless dims.count { |d| stock_section_match?(d) } == 2
        got = dims.map { |d| format('%.2f mm', d.to_mm) }.join(', ')
        raise ArgumentError,
              "EB stock beam: need two section sides (#{BEAM_NARROW.to_mm.round(2)} × #{BEAM_WIDE.to_mm.round(2)} mm), got (#{got})"
      end

      long = dims.find { |d| !stock_section_match?(d) }
      long = long.to_mm.abs
      raise ArgumentError, 'EB stock beam: extrusion length must be > 0' if long <= BEAM_SECTION_TOL_MM

      long
    end

    # All solid stock (legs, slats, caps, sisters, ties) goes through here — validates 44×69 extrusion and tallies metres.
    def add_stock_beam(parent_entities, name, x, y, z, dx, dy, dz, note: nil, layer: nil, count_usage: true)
      extrusion_mm = extrusion_length_mm(dx, dy, dz)
      if count_usage && stock_tally?
        @beam_stock_extrusion_m = (beam_stock_extrusion_m + (extrusion_mm / 1000.0))
        @beam_stock_piece_count = beam_stock_piece_count + 1
        (@beam_stock_cuts ||= []) << { name: name, mm: extrusion_mm }
      end
      add_named_part(parent_entities, name, x, y, z, dx, dy, dz, note: note, layer: layer)
    end

    # Raw box in the given entities’ local space (used inside named wrappers).
    def add_box(entities, x, y, z, dx, dy, dz)
      pts = [
        Geom::Point3d.new(x, y, z),
        Geom::Point3d.new(x + dx, y, z),
        Geom::Point3d.new(x + dx, y + dy, z),
        Geom::Point3d.new(x, y + dy, z)
      ]
      f = entities.add_face(pts)
      f.reverse! if f.normal.z < 0
      f.pushpull(dz)
    end

    # Nested group: shows +name+ in Outliner; optional +note+ on ATTR_DICT (Entity Info → second tab).
    # Use +add_stock_beam+ for all 44×69 stock; this is the low-level primitive only.
    def add_named_part(parent_entities, name, x, y, z, dx, dy, dz, note: nil, layer: nil)
      add_named_part_with_transform(
        parent_entities, name, Geom::Transformation.translation([x, y, z]), dx, dy, dz, note: note, layer: layer
      )
    end

    def add_named_part_with_transform(parent_entities, name, transformation, dx, dy, dz, note: nil, layer: nil)
      g = parent_entities.add_group
      g.name = name
      g.layer = layer if layer
      g.set_attribute(ATTR_DICT, 'note', note) if note && !note.to_s.empty?
      add_box(g.entities, 0, 0, 0, dx, dy, dz)
      g.transformation = transformation
      g
    end

    # Sole entry point for planks: thin dimension along +Y is always PLANK_THICKNESS; name must be EB | plank | …
    module PlankFactory
      module_function

      def add_thin_y(parent_entities, name, x, y, z, dx, dz, layer: nil, note: nil)
        n = name.to_s
        unless ExtendableBed::EB_PLANK_NAME_RE.match?(n)
          raise ArgumentError, "EB plank: name must match /^EB | plank |/, got #{n.inspect}"
        end

        ExtendableBed.add_named_part(parent_entities, n, x, y, z, dx, ExtendableBed::PLANK_THICKNESS, dz, layer: layer, note: note)
      end
    end

    # Sole entry point for pillows: one of dx, dy, dz must equal PILLOW_THICKNESS (foam short edge); name EB | pillow | …
    module PillowFactory
      module_function

      def prism_has_pillow_thickness_edge?(dx, dy, dz)
        t = ExtendableBed::PILLOW_THICKNESS.to_mm.abs
        [dx, dy, dz].any? { |e| (e.to_mm.abs - t).abs < 0.05 }
      end

      def assert_pillow_prism!(dx, dy, dz)
        return if prism_has_pillow_thickness_edge?(dx, dy, dz)

        raise ArgumentError,
              "EB pillow: one of dx, dy, dz must be PILLOW_THICKNESS (#{ExtendableBed::PILLOW_THICKNESS}), got #{dx} × #{dy} × #{dz}"
      end

      # Axis-aligned prism: local box (0..dx, 0..dy, 0..dz) then +transform+ into parent space.
      def add_prism(parent_entities, name, transform, dx, dy, dz, layer: nil, note: nil)
        n = name.to_s
        unless ExtendableBed::EB_PILLOW_NAME_RE.match?(n)
          raise ArgumentError, "EB pillow: name must match /^EB | pillow |/, got #{n.inspect}"
        end

        assert_pillow_prism!(dx, dy, dz)
        ExtendableBed.add_named_part_with_transform(parent_entities, n, transform, dx, dy, dz, layer: layer, note: note)
      end

      # Flat on slats: stock thickness along +Z.
      def add_on_slats(parent_entities, name, x, y, z_slat_top, dx, dy, layer: nil, note: nil)
        add_prism(
          parent_entities, name, Geom::Transformation.translation([x, y, z_slat_top]), dx, dy, ExtendableBed::PILLOW_THICKNESS,
          layer: layer, note: note
        )
      end
    end

    # Big pillow in back-root space; two smalls in front-root space (footward of big). All shifted −Y by BEAM_NARROW
    # so the headward +Y face meets the head plank (footward face of head ledge at y = 0).
    def add_pillows_extended_pair(back_group, front_group, layer: nil)
      m = frame_layout_metrics
      w = m[:w]
      z_top_slats = z_slat_top
      y_pillow = BEAM_Y - BEAM_NARROW

      PillowFactory.add_on_slats(
        back_group.entities,
        PILLOW_BIG,
        0, y_pillow, z_top_slats,
        w, PILLOW_BIG_LENGTH,
        layer: layer,
        note: 'Extended bed only; on slats between planks; +Y edge flush head plank; Y span = retracted outer length.'
      )

      small_len = PILLOW_SMALL_LENGTH
      return unless small_len.to_f > 0.0

      y0 = y_pillow + PILLOW_BIG_LENGTH
      foot_y = EXTENDED_FRONT_FOOT_WORLD_Y

      [PILLOW_SMALL_1, PILLOW_SMALL_2].each_with_index do |name, i|
        # Foot→head order vs previous: pillow 1 sits footward, 2 headward (mirrored along Y in the extension).
        y_world = y0 + ((1 - i) * small_len)
        PillowFactory.add_on_slats(
          front_group.entities,
          name,
          0, y_world - foot_y, z_top_slats,
          w, small_len,
          layer: layer,
          note: "Extended bed only; small #{i + 1}/2; Y order foot→head; (LENGTH_EXTENDED − LENGTH_RETRACTED − BEAM_NARROW)/2 each."
        )
      end
    end

    # Retracted pair: big cushion flat between planks; two small cushions on top — same prism as extended smalls (w × PILLOW_SMALL_LENGTH × PILLOW_THICKNESS), permuted.
    def add_pillows_retracted_pair(back_group, layer: nil)
      m = frame_layout_metrics
      w = m[:w]
      z_top_slats = z_slat_top
      y_pillow = BEAM_Y - BEAM_NARROW
      z_on_big = z_top_slats + PILLOW_THICKNESS
      t = PILLOW_THICKNESS
      sm = PILLOW_SMALL_LENGTH

      PillowFactory.add_on_slats(
        back_group.entities,
        PILLOW_BIG,
        0, y_pillow, z_top_slats,
        w, PILLOW_BIG_LENGTH,
        layer: layer,
        note: 'Retracted bed / couch seat; flat on slats; +Y edge flush head plank; Y span = LENGTH_RETRACTED + BEAM_NARROW (between planks).'
      )

      return unless sm.to_f > 0.0

      # Smaller face (w × T) on the big pillow; height Z = sm — at head (+Y low) end of seat (opposite former foot strip).
      PillowFactory.add_prism(
        back_group.entities,
        PILLOW_COUCH_HEAD,
        Geom::Transformation.translation([0, y_pillow, z_on_big]),
        w, t, sm,
        layer: layer,
        note: 'Couch mode; head end of seat; PILLOW_THICKNESS along Y onto seat; height PILLOW_SMALL_LENGTH along Z.'
      )

      # Same edges as flat small (w, sm, t): thickness along +X at max-X; +Y by T past head strip so no overlap with couch | head.
      y_right = y_pillow + t
      PillowFactory.add_prism(
        back_group.entities,
        PILLOW_COUCH_RIGHT,
        Geom::Transformation.translation([w - t, y_right, z_on_big]),
        t, w, sm,
        layer: layer,
        note: 'Couch mode; +X side; Y0 = y_pillow + PILLOW_THICKNESS clears head cushion band; same prism as small flat pillow.'
      )
    end

    # Half-extended: open span = big + one small flat; vertical head cushion same transform as retracted PILLOW_COUCH_HEAD.
    def add_pillows_halfway_pair(back_group, front_group, layer: nil)
      m = frame_layout_metrics
      w = m[:w]
      z_top_slats = z_slat_top
      y_pillow = BEAM_Y - BEAM_NARROW
      z_on_big = z_top_slats + PILLOW_THICKNESS
      t = PILLOW_THICKNESS
      sm = PILLOW_SMALL_LENGTH
      foot_y = HALFWAY_FRONT_FOOT_WORLD_Y

      PillowFactory.add_on_slats(
        back_group.entities,
        PILLOW_BIG,
        0, y_pillow, z_top_slats,
        w, PILLOW_BIG_LENGTH,
        layer: layer,
        note: 'Half-extended; flat big on slats; +Y edge flush head plank; Y span = PILLOW_BIG_LENGTH (same as retracted).'
      )

      return unless sm.to_f > 0.0

      PillowFactory.add_prism(
        back_group.entities,
        PILLOW_COUCH_HEAD,
        Geom::Transformation.translation([0, y_pillow, z_on_big]),
        w, t, sm,
        layer: layer,
        note: 'Same placement as EB | pillow | couch | head on retracted pair; on big pillow at head end.'
      )

      y0 = y_pillow + PILLOW_BIG_LENGTH
      PillowFactory.add_on_slats(
        front_group.entities,
        PILLOW_SMALL_2,
        0, y0 - foot_y, z_top_slats,
        w, sm,
        layer: layer,
        note: 'Half-extended; single small flat footward of big; fills remaining span to foot plank (same slot as extended small | 2).'
      )
    end

    def find_placement_group_by_name(model, name)
      placement_entities(model).grep(Sketchup::Group).find { |g| g.valid? && g.name == name }
    end

    def slat_starts_along_x
      step = 2 * (SLAT_DX + SLAT_GAP)
      back = (0...BACK_SLAT_COUNT).map { |k| k * step }
      front = (0...FRONT_SLAT_COUNT).map { |j| (SLAT_DX + SLAT_GAP) + j * step }
      [back, front]
    end

    # Left/right comb slats (min and max X start); all slats share SLAT_DX.
    def outermost_comb_slat_x_starts
      back_xs, front_xs = slat_starts_along_x
      merged = back_xs + front_xs
      [merged.min, merged.max]
    end

    # Outer −X/+X of front comb only: min X start and span to outer +X face of last front tooth.
    def front_comb_outer_lo_x_and_span_x
      _, front_xs = slat_starts_along_x
      lo_x = front_xs.min
      hi_x = front_xs.max
      span_x = (hi_x + SLAT_DX) - lo_x
      [lo_x, span_x]
    end

    # Inner X start (past outer −X back tooth) and span to outer +X sister line — for ties between sisters.
    def sister_tie_inner_x1_and_span_x
      lo_x, hi_x = outermost_comb_slat_x_starts
      x1 = lo_x + SLAT_DX
      span_x = hi_x - x1
      [x1, span_x]
    end

    # Fixed (back) frame only: two beams, same plan as the outermost slats, stacked under them (BEAM_Z).
    def add_beams_below_outermost_slats_back(entities, z_slats, layer: nil)
      z_lo = z_slats - BEAM_Z
      # Head legs end at y = BEAM_Y − PLANK_THICKNESS (+Y face); start sisters there so they meet the legs;
      # keep footward end at BEAM_Y + BACK_SLAT_RUN_Y + PLANK_THICKNESS (same as slat run + prior extension).
      y0 = BEAM_Y - PLANK_THICKNESS
      sister_dy = BACK_SLAT_RUN_Y + (2 * PLANK_THICKNESS)
      lo_x, hi_x = outermost_comb_slat_x_starts
      [
        ['EB | beam | sister | outer -X', lo_x, 'at -X'],
        ['EB | beam | sister | outer +X', hi_x, 'at +X']
      ].each do |name, x0, at|
        add_stock_beam(
          entities, name, x0, y0, z_lo, SLAT_DX, sister_dy, BEAM_Z,
          layer: layer,
          note: "Sister under outermost comb slat #{at}; −Y start offset PLANK_THICKNESS to meet head legs; +Y length +2×PLANK_THICKNESS vs BACK_SLAT_RUN_Y; BEAM_Z thick; top flush slat bottom."
        )
      end
    end

    # Four 44×69 prisms, all inside the slat frame in Y:
    # Head legs → beam +Y of leg (y = LEG_Y). Mid legs: plan 44×69 with narrow along X at outer columns;
    # beam sits headward of mid leg −Y face (y = mid_y0 − LEG_X).
    def add_beams_behind_back_legs(entities, mid_y0, lh_corner, lh_mid, layer: nil)
      w = outer_width
      y_behind_head = LEG_Y - PLANK_THICKNESS
      y_behind_mid = mid_y0 - LEG_X
      note_head = '44×69 plan (LEG_Y×LEG_X in X×Y), extruded Z; +Y of head leg; 69 mm along Y on outer ±X face.'
      note_mid = '44×69 plan (LEG_Y×LEG_X in X×Y), extruded Z; −Y of mid leg, headward; 69 mm along Y on outer ±X face.'
      add_stock_beam(
        entities, 'EB | beam | behind leg | head -X',
        0, y_behind_head, 0, LEG_Y, LEG_X, lh_corner,
        layer: layer, note: note_head
      )
      add_stock_beam(
        entities, 'EB | beam | behind leg | head +X',
        w - LEG_Y, y_behind_head, 0, LEG_Y, LEG_X, lh_corner,
        layer: layer, note: note_head
      )
      add_stock_beam(
        entities, HEADWARD_BEHIND_LEG_MID_NEG_X,
        0, y_behind_mid, 0, LEG_Y, LEG_X, lh_mid,
        layer: layer, note: note_mid
      )
      add_stock_beam(
        entities, HEADWARD_BEHIND_LEG_MID_POS_X,
        w - LEG_Y, y_behind_mid, 0, LEG_Y, LEG_X, lh_mid,
        layer: layer, note: note_mid
      )
    end

    # Front frame: one beam under slats 1…N at the foot end; X spans outer faces of first/last front tooth; BEAM_Z up from below.
    def add_beam_under_front_slats_foot_end(entities, z_slats, layer: nil)
      lo_x, span_x = front_comb_outer_lo_x_and_span_x
      y_slat_foot = -BEAM_Y - FRONT_SLAT_RUN_Y
      # Slat footward face at y = y_slat_foot; beam sits BEAM_Y (44 mm) headward — gap from slat foot to beam −Y face.
      # −PLANK_THICKNESS in Y (footward vs prior slat-foot geometry).
      y_beam = y_slat_foot + BEAM_Y - PLANK_THICKNESS
      z_lo = z_slats - BEAM_Z
      add_stock_beam(
        entities,
        'EB | beam | front | under slats | foot end',
        lo_x, y_beam, z_lo, span_x, BEAM_Y, BEAM_Z,
        layer: layer,
        note: 'Under EB | slat | front | 1–8; X from outer −X of slat 1 to outer +X of slat 8; top flush slat bottom; Y offset −PLANK_THICKNESS vs slat-foot geometry; −Y face BEAM_Y headward of slat foot ends.'
      )
    end

    # Second full-width front beam below foot cap (same X span as foot-end slat beam); stiffens foot assembly.
    def add_front_rigidity_beam_below_foot_cap(entities, z_slats, layer: nil)
      lo_x, span_x = front_comb_outer_lo_x_and_span_x
      y_beam = FRONT_RIGIDITY_BEAM_Y0 + PLANK_THICKNESS
      z_lo = z_slats - BEAM_Z
      add_stock_beam(
        entities,
        FRONT_RIGIDITY_BEAM_BELOW_CAP,
        lo_x, y_beam, z_lo, span_x, BEAM_Y, BEAM_Z,
        layer: layer,
        note: 'Same X as EB | beam | front | under slats | foot end; below foot cap band; BEAM_Y × BEAM_Z.'
      )
    end

    # Two ties spanning inner face of outer −X sister to outer +X sister (708 mm in reference geometry).
    def add_head_and_mid_tie_beams_between_sisters(entities, lh_mid, layer: nil)
      x1, span_x = sister_tie_inner_x1_and_span_x
      return if span_x <= 0

      y_head = BEAM_Y - PLANK_THICKNESS
      y_mid = (LENGTH_RETRACTED - (2 * BEAM_Y)) - PLANK_THICKNESS

      add_stock_beam(
        entities,
        HEAD_TIE_BETWEEN_SISTERS,
        x1, y_head, lh_mid, span_x, BEAM_Y, BEAM_Z,
        layer: layer,
        note: 'At head (+Y) end of sister run; same Z as sisters; spans X between outer sister inner faces.'
      )
      add_stock_beam(
        entities,
        'EB | beam | mid tie | between sisters',
        x1, y_mid, lh_mid, span_x, BEAM_Y, BEAM_Z,
        layer: layer,
        note: 'Near mid-run legs (y = LENGTH_RETRACTED − 2×BEAM_Y); same Z as sisters; spans X between outer sister inner faces.'
      )
    end

    # Same 44×69 stock as headward behind-leg mids, rotated: extrusion +Z (lh_mid), LEG_X along +X (parallel to mid tie), BEAM_Y in Y.
    # Sits headward (−Y) of mid-run legs with Y band matching mid tie; +X filler’s +X face flush inner −X of +X mid leg (mirror for −X).
    def add_mid_tie_vertical_fillers_beside_mid_legs(entities, lh_mid, layer: nil)
      w = outer_width
      y_mid = (LENGTH_RETRACTED - (2 * BEAM_Y)) - PLANK_THICKNESS

      add_stock_beam(
        entities,
        MID_TIE_VERTICAL_FILLER_NEG_X,
        LEG_Y, y_mid, 0, LEG_X, BEAM_Y, lh_mid,
        layer: layer,
        note: 'Under EB | beam | mid tie | between sisters; z = 0..lh_mid; inner +X face flush EB | leg | mid run | −X; BEAM_WIDE along +X.'
      )
      add_stock_beam(
        entities,
        MID_TIE_VERTICAL_FILLER_POS_X,
        w - LEG_Y - LEG_X, y_mid, 0, LEG_X, BEAM_Y, lh_mid,
        layer: layer,
        note: 'Under EB | beam | mid tie | between sisters; z = 0..lh_mid; inner −X face flush EB | leg | mid run | +X; BEAM_WIDE along +X.'
      )
    end

    # Axis-aligned overlap in world space (SketchUp inches). Touching faces do not count.
    def aabb_overlap?(bb1, bb2)
      bb1.max.x > bb2.min.x && bb2.max.x > bb1.min.x &&
        bb1.max.y > bb2.min.y && bb2.max.y > bb1.min.y &&
        bb1.max.z > bb2.min.z && bb2.max.z > bb1.min.z
    end

    # World AABB for a group. SketchUp Group#bounds corners are in the *parent* coordinate system
    # (Drawingelement#bounds), not the group's local system — do not multiply by group.transformation.
    def world_bounds_for_group(group, parent_world_tr)
      bb = group.bounds
      wb = Geom::BoundingBox.new
      8.times { |i| wb.add(bb.corner(i).transform(parent_world_tr)) }
      wb
    end

    def collect_eb_solids_world(entities, parent_world_tr, out)
      entities.grep(Sketchup::Group).each do |g|
        next unless g.valid?

        if EB_SOLID_NAME_RE.match?(g.name)
          out << { name: g.name, bb: world_bounds_for_group(g, parent_world_tr), eid: g.entityID }
        end
        collect_eb_solids_world(g.entities, parent_world_tr * g.transformation, out)
      end
    end

    def eb_root_groups(model)
      model.entities.grep(Sketchup::Group).select do |g|
        EB_GROUP_NAME_RE.match?(g.name) || EB_SINGLE_PAIR_ROOTS.include?(g.name)
      end
    end

    # Pairs of named beam/leg groups whose world axis-aligned bounds intersect, scoped per top-level EB root.
    def overlapping_eb_solid_pairs(model = Sketchup.active_model)
      pairs = []
      eb_root_groups(model).each do |root|
        next unless root.valid?

        items = []
        collect_eb_solids_world(root.entities, root.transformation, items)
        (0...items.size).each do |i|
          ((i + 1)...items.size).each do |j|
            a = items[i]
            b = items[j]
            next if a[:eid] == b[:eid]

            pairs << { root: root.name, a: a[:name], b: b[:name] } if aabb_overlap?(a[:bb], b[:bb])
          end
        end
      end
      pairs
    end

    # Prints a one-line summary; returns the overlap list (empty = OK).
    def validate_eb_solids(model = Sketchup.active_model)
      pairs = overlapping_eb_solid_pairs(model)
      if pairs.empty?
        puts '[EB validate] OK — no beam/leg bounding-box overlaps within each EB root.'
      else
        puts "[EB validate] #{pairs.size} overlapping beam/leg pair(s):"
        pairs.each { |p| puts "  #{p[:root]}: #{p[:a]}  ⟷  #{p[:b]}" }
      end
      pairs
    end

    def clear(model = Sketchup.active_model)
      exit_edit_context!(model)
      roots = placement_entities(model)
      purge_named_groups_recursive(roots, BEHIND_LEG_MID_UNQUALIFIED_NAMES, skip_reference_subtrees: true)
      to_erase = roots.grep(Sketchup::Group).select do |g|
        EB_GROUP_NAME_RE.match?(g.name) || EB_SINGLE_PAIR_ROOTS.include?(g.name)
      end
      to_erase.each(&:erase!)
    end

    # Shared Z chain, leg heights, and cap X span for both frame halves (back / front local space).
    def frame_layout_metrics
      w = outer_width
      z_low = z_slat_bottom
      {
        w: w,
        z_low: z_low,
        zlt: z_leg_top,
        lh: leg_height,
        lh_corner_through_cap: outer_corner_leg_height_through_cap,
        cap_x0: LEG_X,
        cap_dx: w - (2 * LEG_X)
      }
    end

    def build_back_group(model, name:)
      layer = ensure_layer(model)
      g = placement_entities(model).add_group
      g.name = name
      g.layer = layer
      e = g.entities
      m = frame_layout_metrics
      w = m[:w]
      z_low = m[:z_low]
      lh = m[:lh]
      lh_head_outer = m[:lh_corner_through_cap]
      lh_mid = mid_run_leg_height(z_low)
      zlt = m[:zlt]
      cap_x0 = m[:cap_x0]
      cap_dx = m[:cap_dx]
      y_head = -PLANK_THICKNESS

      add_stock_beam(e, 'EB | leg | head | -X', 0, y_head, 0, LEG_X, LEG_Y, lh_head_outer,
                     layer: layer,
                     note: 'Corner leg at head (+Y), -X; extruded to top of head cap; inner +X face bears cap end.')
      add_stock_beam(e, 'EB | leg | head | +X', w - LEG_X, y_head, 0, LEG_X, LEG_Y, lh_head_outer,
                     layer: layer,
                     note: 'Corner leg at head (+Y), +X; extruded to top of head cap; inner −X face bears cap end.')

      mid_y0 = (LENGTH_RETRACTED - LEG_X) + PLANK_THICKNESS
      add_stock_beam(e, 'EB | leg | mid run | -X', 0, mid_y0, 0, LEG_Y, LEG_X, lh_mid,
                     layer: layer,
                     note: 'Mid-span leg, -X; 44 mm along X at outer column, 69 mm along Y; top flush with sister bottom.')
      add_stock_beam(e, 'EB | leg | mid run | +X', w - LEG_Y, mid_y0, 0, LEG_Y, LEG_X, lh_mid,
                     layer: layer,
                     note: 'Mid-span leg, +X; mirror of −X mid run leg.')

      # Inset copies flush on the inner ±X faces of the outer legs (same stock/heights) for extra stiffness.
      add_stock_beam(e, 'EB | leg | head | -X | inset', LEG_X, y_head, 0, LEG_X, LEG_Y, lh,
                     layer: layer,
                     note: 'Inset strengthener; duplicate of EB | leg | head | -X, +X of its inner face.')
      add_stock_beam(e, 'EB | leg | head | +X | inset', w - (2 * LEG_X), y_head, 0, LEG_X, LEG_Y, lh,
                     layer: layer,
                     note: 'Inset strengthener; duplicate of EB | leg | head | +X, −X of its inner face.')

      # Head behind-leg beams stay at +leg_height+ so they do not occupy the same Z band as EB | beam | sister | outer ±X.
      add_beams_behind_back_legs(e, mid_y0, lh, lh_mid, layer: layer)

      add_stock_beam(e, 'EB | beam | head | cap', cap_x0, y_head, zlt, cap_dx, BEAM_Y, BEAM_Z,
                     layer: layer,
                     note: 'Head cap between outer legs: X from inner face of head | -X to inner face of head | +X; BEAM_Y × BEAM_Z in Y×Z.')

      # Head end of bed: Y band y_head..y_head+PLANK_THICKNESS (flush headward with shifted head cap / corner legs); same X/Z as foot plank.
      PlankFactory.add_thin_y(
        e,
        PLANK_HEAD_LEDGE,
        0, y_head, z_low, w, (2 * BEAM_WIDE),
        layer: layer,
        note: 'Sits on top of EB | beam | head | cap and EB | leg | head | ±X; full bed width; headward face flush with bed end; top BEAM_WIDE above slat tops.'
      )

      add_stock_beam(e, 'EB | beam | head | end', 0, 0, z_low, w, BEAM_Y, BEAM_Z,
                     layer: layer,
                     note: 'Head end beam 44×69 mm (BEAM_Y × BEAM_Z); under cap.')

      back_xs, = slat_starts_along_x
      y0 = BEAM_Y
      back_xs.each_with_index do |x0, i|
        add_stock_beam(
          e,
          format('EB | slat | back | %d/%d', i + 1, BACK_SLAT_COUNT),
          x0, y0, z_low, SLAT_DX, BACK_SLAT_RUN_Y, SLAT_DZ,
          layer: layer,
          note: 'Back (fixed) comb tooth; interlocks with front slats when assembled.'
        )
      end

      add_beams_below_outermost_slats_back(e, z_low, layer: layer)
      add_head_and_mid_tie_beams_between_sisters(e, lh_mid, layer: layer)
      add_mid_tie_vertical_fillers_beside_mid_legs(e, lh_mid, layer: layer)

      paint_root_group_preview_color(g, model, EB_PREVIEW_RGB_BACK, EB_PREVIEW_MAT_BACK)
      g
    end

    def build_front_geometry(entities, layer: nil)
      m = frame_layout_metrics
      w = m[:w]
      z_low = m[:z_low]
      lh = m[:lh]
      lh_foot_outer = m[:lh_corner_through_cap]
      zlt = m[:zlt]
      cap_x0 = m[:cap_x0]
      cap_dx = m[:cap_dx]
      y_foot_protrude = -BEAM_Y + PLANK_THICKNESS

      add_stock_beam(entities, 'EB | leg | foot | -X', 0, y_foot_protrude, 0, LEG_X, LEG_Y, lh_foot_outer,
                     layer: layer,
                     note: 'Corner leg at foot (-Y), -X; extruded to top of foot cap so inner +X face bears cap end.')
      add_stock_beam(entities, 'EB | leg | foot | +X', w - LEG_X, y_foot_protrude, 0, LEG_X, LEG_Y, lh_foot_outer,
                     layer: layer,
                     note: 'Corner leg at foot, +X; extruded to top of foot cap; inner −X face bears cap end.')

      add_stock_beam(entities, 'EB | leg | foot | -X | inset', LEG_X, y_foot_protrude, 0, LEG_X, LEG_Y, lh,
                     layer: layer,
                     note: 'Inset strengthener; duplicate of EB | leg | foot | -X, +X of its inner face.')
      add_stock_beam(entities, 'EB | leg | foot | +X | inset', w - (2 * LEG_X), y_foot_protrude, 0, LEG_X, LEG_Y, lh,
                     layer: layer,
                     note: 'Inset strengthener; duplicate of EB | leg | foot | +X, −X of its inner face.')

      add_stock_beam(entities, 'EB | beam | foot | cap', cap_x0, y_foot_protrude, zlt, cap_dx, BEAM_Y, BEAM_Z,
                     layer: layer,
                     note: 'Foot cap between outer legs: X from inner face of foot | -X to inner face of foot | +X; BEAM_Y × BEAM_Z in Y×Z.')

      # Non-stock front plank: shifted foot-cap/leg ledge (Y: 0..PLANK_THICKNESS); full width; 2×BEAM_WIDE in Z.
      PlankFactory.add_thin_y(
        entities,
        PLANK_FOOT_LEDGE,
        0, 0, z_low, w, (2 * BEAM_WIDE),
        layer: layer,
        note: 'Sits on top of EB | beam | foot | cap and EB | leg | foot | ±X; full bed width; top BEAM_WIDE above slat tops.'
      )

      add_stock_beam(entities, 'EB | beam | foot | end', 0, -BEAM_Y, z_low, w, BEAM_Y, BEAM_Z,
                     layer: layer,
                     note: 'Foot end beam 44×69 mm (BEAM_Y × BEAM_Z); under cap.')

      _, front_xs = slat_starts_along_x
      y1 = -BEAM_Y - FRONT_SLAT_RUN_Y
      front_xs.each_with_index do |x0, i|
        add_stock_beam(
          entities,
          format('EB | slat | front | %d/%d', i + 1, FRONT_SLAT_COUNT),
          x0, y1, z_low, SLAT_DX, FRONT_SLAT_RUN_Y, SLAT_DZ,
          layer: layer,
          note: 'Front (sliding) comb tooth; sits in gaps of back slats; Y run = FRONT_SLAT_RUN_Y (SLAT_LENGTH + BEAM_Y).'
        )
      end

      add_beam_under_front_slats_foot_end(entities, z_low, layer: layer)
      add_front_rigidity_beam_below_foot_cap(entities, z_low, layer: layer)
    end

    def build_front_group(model, name:, foot_world_y:, offset_x: 0)
      layer = ensure_layer(model)
      g = placement_entities(model).add_group
      g.name = name
      g.layer = layer
      build_front_geometry(g.entities, layer: layer)
      paint_root_group_preview_color(g, model, EB_PREVIEW_RGB_FRONT, EB_PREVIEW_MAT_FRONT)
      g.transformation = Geom::Transformation.translation([offset_x, foot_world_y, 0])
      g
    end

    def place_pair(model, offset_x:, foot_world_y:, back_name:, front_name:)
      b = build_back_group(model, name: back_name)
      b.transformation = Geom::Transformation.translation([offset_x, 0, 0])
      build_front_group(model, name: front_name, foot_world_y: foot_world_y, offset_x: offset_x)
    end

    def create(model = Sketchup.active_model)
      model.start_operation('Extendable bed', true)
      clear(model)
      reset_beam_stock_usage!
      w = outer_width
      gap = PAIR_GAP_X
      place_pair(
        model,
        offset_x: 0,
        foot_world_y: EXTENDED_FRONT_FOOT_WORLD_Y,
        back_name: GROUP_EXT_BACK,
        front_name: GROUP_EXT_FRONT
      )
      layer = ensure_layer(model)
      back_g = find_placement_group_by_name(model, GROUP_EXT_BACK)
      front_g = find_placement_group_by_name(model, GROUP_EXT_FRONT)
      add_pillows_extended_pair(back_g, front_g, layer: layer) if back_g && front_g

      @eb_stock_tally = false
      place_pair(
        model,
        offset_x: w + gap,
        foot_world_y: HALFWAY_FRONT_FOOT_WORLD_Y,
        back_name: GROUP_HALF_BACK,
        front_name: GROUP_HALF_FRONT
      )
      half_back = find_placement_group_by_name(model, GROUP_HALF_BACK)
      half_front = find_placement_group_by_name(model, GROUP_HALF_FRONT)
      add_pillows_halfway_pair(half_back, half_front, layer: layer) if half_back && half_front

      place_pair(
        model,
        offset_x: 2 * (w + gap),
        foot_world_y: RETRACTED_FOOT_WORLD_Y,
        back_name: GROUP_RET_BACK,
        front_name: GROUP_RET_FRONT
      )
      ret_back = find_placement_group_by_name(model, GROUP_RET_BACK)
      add_pillows_retracted_pair(ret_back, layer: layer) if ret_back

      model.commit_operation
      model.active_view.invalidate
      validate_eb_solids(model)
      m = beam_stock_extrusion_m
      n = beam_stock_piece_count
      puts format('[EB stock] %.3f m extrusion, %d pieces — one bed (%s + %s). Retracted / half-extended preview pairs are not counted.',
                  m, n, GROUP_EXT_BACK, GROUP_EXT_FRONT)
      puts_beam_stock_cut_plan
    end
  end
end
